export const citys = [
  { name: "Alagoinhas", value: "Alagoinhas" },
  { name: "Barreiras", value: "Barreiras" },
  { name: "Bom Jesus da Lapa", value: "Bom Jesus da Lapa" },
  { name: "Botuporã", value: "Botuporã" },
  { name: "Brumado", value: "Brumado" },
  { name: "Caculé", value: "Caculé" },
  { name: "Caetité", value: "Caetité" },
  { name: "Camaçari", value: "Camaçari" },
  { name: "Candiba", value: "Candiba" },
  { name: "Carinhanha", value: "Carinhanha" },
  { name: "Feira de Santana", value: "Feira de Santana" },
  { name: "Guanambi", value: "Guanambi" },
  { name: "Igaporã", value: "Igaporã" },
  { name: "Ilhéus", value: "Ilhéus" },
  { name: "Iuiu", value: "Iuiu" },
  { name: "Itabuna", value: "Itabuna" },
  { name: "Iuiú", value: "Iuiú" },
  { name: "Jequié", value: "Jequié" },
  { name: "Jacaraci", value: "Jacaraci" },
  { name: "Juazeiro", value: "Juazeiro" },
  { name: "Licínio de Almeida", value: "Licínio de Almeida" },
  { name: "Livramento de Nossa Senhora", value: "Livramento de Nossa Senhora" },
  { name: "Lauro de Freitas", value: "Lauro de Freitas" },
  { name: "Macaúbas", value: "Macaúbas" },
  { name: "Malhada", value: "Malhada" },
  { name: "Matina", value: "Matina" },
  { name: "Mortugaba", value: "Mortugaba" },
  { name: "Palmas de Monte Alto", value: "Palmas de Monte Alto" },
  { name: "Pindaí", value: "Pindaí" },
  { name: "Pindorama", value: "Pindorama" },
  { name: "Porto Seguro", value: "Porto Seguro" },
  { name: "Riacho de Santana", value: "Riacho de Santana" },
  { name: "Rio do Antônio", value: "Rio do Antônio" },
  { name: "Salvador", value: "Salvador" },
  { name: "Sebastião Laranjeiras", value: "Sebastião Laranjeiras" },
  { name: "Tanque Novo", value: "Tanque Novo" },
  { name: "Tremedal", value: "Tremedal" },
  { name: "Urandi", value: "Urandi" },
  { name: "Vitória da Conquista", value: "Vitória da Conquista" },
];
